name: market-data-feed

on:
  workflow_dispatch:
#  schedule:
#    - cron: '30 * * * *' #Execute every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2

      - name: Adjust permissions
        run: sudo chmod -R u+w,o+w,g+w ./

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install necessary libraries
        run: |
          cd scripts
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        env:
          URI: ${{ secrets.URI }}
        run: python scripts/market_source.py
      
      - name: Add pickle file to staging area
        run: git add .

      - name: Commit pickle file to repository
        run: git commit -m "market data source update"

      - name: Set GitHub personal access token and push
        env:
          GITHUB_TOKEN: ${{ secrets.STOCKS_APP_TOKEN }}
        run: git push
