name: update-guru-data

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Access the repo
        uses: actions/checkout@v2

      - name: Configure Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install necessary libraries
        run: |
          cd scripts/guru_query
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python Script
        env:
          URI: ${{ secrets.URI }}
        run: python -m scripts.guru_query.guru_query

      - name: Set git globals as correct user
        run: |
          git config --global user.email "7chris.jackson@gmail.com"
          git config --global user.name "Chris"
          
      - name: Add pickle file to staging area
        run: |
          git pull
          git add .
          git commit -m "guru focus source update"

      - name: Set GitHub personal access token and push
        env:
          GITHUB_TOKEN: ${{ secrets.STOCKS_APP_TOKEN }}
        run: git push